<?php
define('APP_NAME', 'NovaBank');
define('APP_CURRENCY', 'NOVA');
define('APP_BASE_URL', '/novabank');

define('MAX_LOGIN_ATTEMPTS', 5);
define('LOGIN_LOCKOUT_MINUTES', 15);
define('LOGIN_ATTEMPT_WINDOW_MINUTES', 15);

define('SESSION_IDLE_TIMEOUT_MINUTES', 30);

define('MIN_TRANSACTION_AMOUNT', 1.00);
define('MAX_TRANSACTION_AMOUNT', 500000.00);
define('MAX_DEPOSIT_AMOUNT', 500000.00);

define('LOAN_INTEREST_RATE', 5.00);
define('LOAN_MIN_AMOUNT', 1000.00);
define('LOAN_MAX_AMOUNT', 100000.00);
define('LOAN_MIN_TERM_MONTHS', 3);
define('LOAN_MAX_TERM_MONTHS', 36);

define('RATE_LIMIT_TRANSFER_PER_HOUR', 20);
define('RATE_LIMIT_LOAN_APPLICATIONS_PER_DAY', 3);

define('PASSWORD_MIN_LENGTH', 8);
